# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
dist: trusty   # Use Ubuntu 14.04 image (instead of 12.04)
language: r
sudo: false
r: 4.0.0

install:
  - R -e 'if (system.file(package="packrat") == "") install.packages("packrat")'
  - R -e "packrat::packify(); packrat::restore()"

cache:
  packages: true
  directories:
    - packrat/lib
# Install packrat if needed and have it restore packages.
#install:
#  - R -e "0" --args --bootstrap-packrat
#  - R -e "packrat::restore(restart = FALSE)"

#cache:
#  # Main R library
#  packages: true
#  directories:
#    # Packrat packages
#    - $TRAVIS_BUILD_DIR/packrat/lib
#    - $TRAVIS_BUILD_DIR/packrat/src


script:
  - R -f run_tests.R